ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER s1_transilvania IDENTIFIED BY parola123;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE DATABASE LINK TO s1_transilvania;
ALTER USER s1_transilvania QUOTA UNLIMITED ON USERS;

CREATE USER s2_muntenia IDENTIFIED BY parola123;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE DATABASE LINK TO s2_muntenia;
ALTER USER s2_muntenia QUOTA UNLIMITED ON USERS;

CREATE USER s3_moldova IDENTIFIED BY parola123;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE DATABASE LINK TO s3_moldova;
ALTER USER s3_moldova QUOTA UNLIMITED ON USERS;

CREATE USER s_global IDENTIFIED BY parola123;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE DATABASE LINK TO s_global;
ALTER USER s_global QUOTA UNLIMITED ON USERS;